### ISSUE TITLE
Alternative PHP implementation

### ISSUE THREAD

**Issue by SamMousa** [famzah/langs-performance#11]
It would be great to show the performance of PHP when using the optimized `SplFixedArray` (http://php.net/manual/en/class.splfixedarray.php).

Considering you're creating the array and then accessing all indices, that's a lot of hashes PHP has to calculate.
Using the `SplFixedArray` should speed that up a lot.

**Comment by famzah** [comment]
Hi Sam,

You are right. Using a pre-allocated fixed array will speed things up for PHP and for the other languages which support this. But the main purpose of the test is to benchmark "loops, dynamic arrays with numbers, basic math operations".

Therefore, pre-allocated fixed arrays is an interesting benchmark, so that we can see how much faster PHP will do. But I cannot accept this optimization in the upsteam tests.

If you implement the SplFixedArray test, please run the original and your versions, and then provide the timing results at the blog page, so that everyone can benefit from your work: https://blog.famzah.net/2016/09/10/cpp-vs-python-vs-php-vs-java-vs-others-performance-benchmark-2016-q3/

Thank you.
